DROP DATABASE IF EXISTS kanaka;
CREATE DATABASE kanaka;
USE kanaka;

DROP TABLE IF EXISTS users;
CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(100) NOT NULL, -- User , Admin
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS refreshTokens;
CREATE TABLE refreshTokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    refreshToken VARCHAR(255) NOT NULL,
    userId INT NOT NULL,
    FOREIGN KEY(userId) REFERENCES users(id)
);

DROP TABLE IF EXISTS invalidTokens;
CREATE TABLE invalidTokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    accessToken VARCHAR(255) NOT NULL,
    userId INT NOT NULL,
    expirationTime BIGINT NOT NULL
);

DROP TABLE IF EXISTS vendedor;
CREATE TABLE vendedor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    apellido VARCHAR(100),
    cedula VARCHAR(100),
    direccion VARCHAR(255),
    telefono VARCHAR(100),
    email VARCHAR(100),
    estado VARCHAR(100) DEFAULT 'ACTIVO', -- Activo, Inactivo
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
